site_name: Space . JaZzyzJ
site_url: https://jazzyzj.github.io/
repo_name: JaZzyzJ.Space
repo_url: https://github.com/JazZyzJ/JazZyzJ.github.io

theme: 
  name: material
  language: en
  icon:
    logo: material/notebook-outline
  features:
    - content.code.annotate
    - content.code.line_numbers
    - content.code.copy
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.top
    # - navigation.footer
    # - navigation.sections
    # - navigation.prune
  
  palette:
    # - custom_dir: docs/css/stylesheets/extra.css
    - scheme: 
      primary: white
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font:
    text: "PT Serif"
    code: "JetBrains Mono, Consolas"


    
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js


extra_css:
  - docs/css/stylesheets/extra.css




nav:
  - Home: index.md
  - N0tes:
      - Computer Science:
        - notes/cs/index.md
        - DS & Algorithms:
          - FDS: notes/cs/algorithm/fds/fds.md
          - ADS: notes/cs/algorithm/ads/ADS.md
          - Backtracking: notes/cs/algorithm/backtracking.md
          - Divide & Conquer: notes/cs/algorithm/DandC.md
          - Dynamic Programming: notes/cs/algorithm/dp.md
          - Greedy Algorithms: notes/cs/algorithm/gdy.md
        - System:
          - CO: 
            - notes/cs/Sys/CO/index.md
            - notes/cs/Sys/CO/arithmetic.md
            - notes/cs/Sys/CO/instruction.md
            - notes/cs/Sys/CO/processor.md
        - PL: 
          - Verilog: notes/lingo/verilog.md
          - Python(CS61a): notes/lingo/cs61a.md
      # - Artifical Intelligence:
  - To0l Box:
    - Workflow:
      - Coding:
        - GNU Make: Tool_Pool/GNU_Make.md
    # - Widgets:
      