site_name: Space . JaZzyzJ
site_url: https://jazzyzj.github.io/
repo_name: JaZzyzJ.Space
repo_url: https://github.com/JazZyzJ/JazZyzJ.github.io
use_directory_urls: false



theme: 
  name: material
  language: en
  favicon: assets/pics/logo.png
  icon: 
    logo: material/book-open-variant
  features:
    - content.code.annotate
    - content.code.line_numbers
    - content.code.copy
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.top
    # - navigation.footer
    # - navigation.sections
    # - navigation.prune
  
  palette:
    # - custom_dir: docs/css/stylesheets/extra.css
    - scheme: 
      primary: white
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font:
    text: "PT Serif"
    code: "JetBrains Mono, Consolas"


    
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js


extra_css:
  - css/stylesheets/extra.css

# plugins:
#   - search
#   - toc
#   - statistics:
#       page_template: "stylesheets/template.html"
#       page_check_metadata: counter  # 检查页面元数据
#       page_count_strict: "true"    # 严格计数模式
#       count_pages: "true"          # 统计页面数
#       count_words: "true"          # 统计字数
#       count_chinese_words: "true"  # 统计中文字数
#       count_code_lines: "true"     # 统计代码行数
#       read_time: "true"           # 估计阅读时间

nav:
  - Home: index.md
  - N0tes:
      - Computer Science:
        - notes/cs/index.md
        - DS & Algorithms:
          - FDS: notes/cs/algorithm/fds/fds.md
          - ADS: notes/cs/algorithm/ads/ADS.md
          - Amortized Analysis: notes/cs/algorithm/ads/amortize.md
          - Backtracking: notes/cs/algorithm/backtracking.md
          - Divide & Conquer: notes/cs/algorithm/DandC.md
          - Dynamic Programming: notes/cs/algorithm/dp.md
          - Greedy Algorithms: notes/cs/algorithm/gdy.md
          - NP Completeness: notes/cs/algorithm/NP.md
          - Approximation: notes/cs/algorithm/Approximation.md
          - Local Search: notes/cs/algorithm/localsearch.md
          - Randomized: notes/cs/algorithm/random.md
          - Parallel: notes/cs/algorithm/para.md
          - External Sort: notes/cs/algorithm/external.md
        - System:
          - CO: 
            - notes/cs/Sys/CO/index.md
            - Arithmetic: notes/cs/Sys/CO/arithmetic.md
            - Instruction: notes/cs/Sys/CO/instruction.md
            - Processor: notes/cs/Sys/CO/processor.md
            - Memory: notes/cs/Sys/CO/memory.md
        - PL: 
          - Verilog: notes/lingo/verilog.md
          - Python(CS61a): notes/lingo/cs61a.md
      # - Artifical Intelligence:
  - To0l Box:
    - Workflow:
      - Coding:
        - GNU Make: Tool_Pool/GNU_Make.md
  - L0g: log/index.md
    
    # - Widgets:
      