site_name: Space . JaZzyzJ
site_url: https://jazzyzj.github.io/
repo_name: JaZzyzJ.Space
repo_url: https://github.com/JazZyzJ/JazZyzJ.github.io

theme: 
  name: material
  language: en
  icon:
    logo: material/notebook-outline
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.top
  
  palette:
    # - custom_dir: docs/css/stylesheets/extra.css
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: 
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font:
    text: "PT Serif"
    code: "JetBrains Mono"

# nav:
#   - Home: index.md
#   - notes: 
#     - Computer Science: 
#       - notes/cs/index.md
#       - Algorithms: 
#         - FDS: notes/cs/algorithm/fds.md   -->Error:fds.md should be fds/fds.md
    
nav:
  - Home: index.md
  - notes:
      - Computer Science:
        - notes/cs/index.md
        - DS & Algorithms:
          - FDS: notes/cs/algorithm/fds/fds.md
          - ADS: notes/cs/algorithm/ads/ADS.md
        - System:
          - CO: notes/cs/Sys/CO.md
        - PL: 
          - Verilog: notes/lingo/verilog.md
          - Python(CS61a): notes/lingo/cs61a.md
      # - Artifical Intelligence:
      - Tools:
        - GNU Make: notes/Tool_Pool/GNU_Make.md




    

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js


extra_css:
  - docs/css/custom.css